### ISSUE TITLE
Unexpected token occurs when starts server

### ISSUE THREAD

**Issue by yaozzzhao** [sin1ght/rss-web#2]
>> node app.js
/root/git/rss-web/server/routes/category.js:60
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/git/rss-web/server/routes/index.js:9:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

**Comment by sin1ght** [comment]
可能是应该是try { } catch (e) {}
但是我没有这样问题 可能和node版本有问题
你再重新拉一下 试试 我改了一下
